exports.prendasGenerales = [
  { text: 'BERMUDA' },
  { text: 'BODIES' },
  { text: 'BOLSO' },
  { text: 'BOXER' },
  { text: 'BRASIER' },
  { text: 'BUZOS' },
  { text: 'CHAQUETAS' },
  { text: 'CAMISAS' },
  { text: 'CAMISETAS' },
  { text: 'CROP_TOPS' },
  { text: 'ENTERIZO' },
  { text: 'FALDAS' },
  { text: 'JEANS' },
  { text: 'LEGINGS' },
  { text: 'OVEROLES' },
  { text: 'PANOLETAS' },
  { text: 'PANTALONES' },
  { text: 'PANTALONETAS' },
  { text: 'PANTIES' },
  { text: 'PIJAMAS_CAMISETAS' },
  { text: 'PIJAMAS_PANTALON' },
  { text: 'PIJAMAS_VESTIDO' },
  { text: 'POLOS' },
  { text: 'SHORTS' },
  { text: 'SUDADERA' },
  { text: 'TENIS' },
  { text: 'TOPS' },
  { text: 'VESTIDOS' },
  { text: 'VESTIDO_DE_BANO_BRASIER' },
  { text: 'VESTIDO_DE_BANO_TANGA' },
  { text: 'ZAPATOS' },
];

exports.mainColors = [
  {
    value: 'rojo',
    hexa: '#fd0000',
    rgb: '(253, 0, 0)',
    hsl: '(0, 100%, 50%)',
  },
  {
    value: 'amarillo',
    hexa: '#fdd500',
    rgb: '(253, 213, 0)',
    hsl: '(51, 100%, 50%)',
  },
  {
    value: 'azul',
    hexa: '#290c96',
    rgb: '( 41, 12, 150 )',
    hsl: '(253, 92%, 32%)',
  },
  {
    value: 'morado',
    hexa: '#7e0c96',
    rgb: '(126, 12, 150)',
    hsl: '(290, 92%, 32%)',
  },
  {
    value: 'naranjado',
    hexa: '#ec7335',
    rgb: '(236, 115, 53)',
    hsl: '(20, 78%, 57%)',
  },
  {
    value: 'verde',
    hexa: '#56a435',
    rgb: '(86, 164, 53)',
    hsl: '(102, 68%, 43%)',
  },
  {
    value: 'negro',
    hexa: '#000000',
    rgb: '(0, 0, 0)',
    hsl: '(0, 0%, 0%)',
  },
  {
    value: 'blanco',
    hexa: '#fffffe',
    rgb: '(255, 255, 254)',
    hsl: '(60, 0%, 100%)',
  },
  {
    value: 'gris',
    hexa: '#4b5154',
    rgb: '(75, 81, 84)',
    hsl: '(200, 11%, 31%)',
  },
  {
    value: 'beige',
    hexa: '#feffd4',
    rgb: '(254, 255, 212)',
    hsl: '(61, 17%, 92%)',
  },
  {
    value: 'rosado',
    hexa: '#fed4d4',
    rgb: '(254, 212, 212)',
    hsl: '( 0, 17%, 91% )',
  },
  {
    value: 'cafe',
    hexa: '#815140',
    rgb: '(129, 81, 64)',
    hsl: '(16, 50%, 38%)',
  },
];


exports.subCategoria = [
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa interior',
  'ropa interior',
  'ropa interior', 
  'ropa interior', 
  'ropa interior', 
  'calzado',
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'calzado',
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa interior',
  'calzado',
  'accesorios', 
  'accesorios',
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa interior',
  'ropa interior', 
  'ropa interior', 
  'ropa interior',
  'ropa interior', 
  'calzado',
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'calzado',
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa interior', 
  'ropa interior', 
  'ropa interior', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa interior',
  'ropa interior', 
  'ropa interior', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'calzado',
  'accesorios', 
  'accesorios', 
  'accesorios',
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa interior',
  'ropa interior', 
  'ropa interior', 
  'ropa interior', 
  'ropa interior', 
  'accesorios',
  'calzado',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa interior',
  'ropa interior', 
  'ropa interior', 
  'accesorios',
  'ropa exterior',
  'calzado',
  'ropa exterior'
  
]

exports.tipoPrenda = [
  'camisas',
  'camisetas',
  'polos',
  'jeans',
  'pantalones',
  'joggers',
  'shorts',
  'bermudas', 
  'faldas',
  'vestidos',
  'chaquetas',
  'buzos',
  'pijamas',
  'panties',
  'brassier',
  'tops',
  'medias',
  'calzado',
  'bolsos',
  'bisutería',
  'cuidado personal',
  'relojes',
  'otros accesorios',
  'blazers',
  'chalecos',
  'cazadoras',
  'sobrecamisas',
  'bombers',
  'abrigos',
  'trench',
  'plumiferos', 
  'acolchados',
  'chalecos',
  'vestidos', 
  'monos',
  'tops',
  'camisas',
  'bluzas',
  'camisetas',
  'sudaderas',
  'polo',
  'pantalones',
  'pantalones de vestir',
  'leggings',
  'joggers',
  'fluidos',
  'jeans',
  'faldas',
  'bermudas',
  'zapatos',
  'bolsos',
  'pet collectionnew',
  'yoga collectionnew',
  'perfumes',
  'bisutería',
  'cinturones',
  'gorros | sombreros',
  'pañuelos',
  'gafas de sol',
  'calcetines',
  'perfumes',
  'abrigos',
  'chaquetas',
  'jerséis',
  'cardigans',
  'chalecos', 
  'americanas',
  'acolchadas',
  'cazadoras',
  'sobrecamisas',
  'vaqueras',
  'piel',
  'vestidos', 
  'monos',
  'camisas',
  'bluzas',
  'camisetas', 
  'tops',
  'sudaderas',
  'pantalones',
  'leggings',
  'joggers',
  'vaqueros',
  'faldas',
  'shorts',
  'bodys',
  'zapatos',
  'bolsos',
  'paraguas',
  'calcetines',
  'accesosorios para el pelo',
  'otros accesorios',
  'gorros', 
  'mascarillas', 
  'bufandas',
  'pañuelos',
  'bisutería',
  'marroquinería',
  'cinturones',
  'gafas de sol',
  'camisas',
  'camisetas',
  'polos',
  'jeans',
  'pantalones',
  'joggers',
  'bermudas',
  'buzos',
  'chaquetas',
  'pijamas',
  'bóxer',
  'pantaloncillos',
  'camisetas',
  'medias',
  'calzado',
  'correas',
  'gorras',
  'relojes',
  'otros accesorios',
  'gabardinas',
  'abrigos',
  'parkas',
  'trench',
  'cazadoras',
  'sobrecamisas',
  'chalecos',
  'blazers',
  'jerséis',
  'chaquetas',
  'cardigans',
  'chándal',
  'sudaderas',
  'camisas',
  'camisetas',
  'polos',
  'pantalones',
  'joggers',
  'chinos',
  'jeans',
  'bermudas',
  'zapatos',
  'bolsos',
  'mochilas',
  'perfumes',
  'gorras y gorros',
  'gafas de sol',
  'boxer',
  'pijamas',
  'calcetines',
  'corbatas y pajaritas',
  'cinturones',
  'porta teléfonos y accesorios',
  'carteras',
  'bufandas y foulards',
  'bisuteria', 
  'relojes',
  'pet collectionnew',
  'abrigos',
  'chaquetas',
  'cardigans', 
  'jerseis',
  'chalecos',
  'trench',
  'parkas',
  'camisas',
  'pantalones',
  'vaqueros',
  'sobrecamisas',
  'americanas',
  'sudaderas',
  'camisetas',
  'bañadores',
  'pijamas', 
  'calzoncillos',
  'calcetines', 
  'americanas',
  'pantalones',
  'camisas',
  'zapatos',
  'mochilas',
  'bolsos',
  'carteras',
  'bufandas', 
  'fulares',
  'gorros', 
  'guantes', 
  'cinturones',
  'tirantes', 
  'corbatas', 
  'pajaritas',
  'gafas de sol',
  'pulseras', 
  'anillos',
  'más accesorios',
  'camisas',
  'camisetas',
  'pantalones',
  'jeans', 
  'leggins',
  'shorts',
  'faldas',
  'vestidos', 
  'buzos',
  'chaquetas', 
  'conjuntos',
  'pijamas',
  'tops',
  'panties',
  'vestido de baño',
  'medias',
  'accesorios',
  'zapatos',
  'camisas',
  'camisetas',
  'polos',
  'pantalones',
  'jeans',
  'joggers',
  'bermudas',
  'buzos',
  'chaquetas',
  'conjuntos',
  'pijamas',
  'boxer',
  'medias',
  'accesorios',
  'beachwear',
  'calzado',
  'trench y parkas'

]
