exports.prendasGenerales = [
  { text: 'BERMUDA' },
  { text: 'BODIES' },
  { text: 'BOLSO' },
  { text: 'BOXER' },
  { text: 'BRASIER' },
  { text: 'BUZOS' },
  { text: 'CHAQUETAS' },
  { text: 'CAMISAS' },
  { text: 'CAMISETAS' },
  { text: 'CROP_TOPS' },
  { text: 'ENTERIZO' },
  { text: 'FALDAS' },
  { text: 'JEANS' },
  { text: 'LEGINGS' },
  { text: 'OVEROLES' },
  { text: 'PANOLETAS' },
  { text: 'PANTALONES' },
  { text: 'PANTALONETAS' },
  { text: 'PANTIES' },
  { text: 'PIJAMAS_CAMISETAS' },
  { text: 'PIJAMAS_PANTALON' },
  { text: 'PIJAMAS_VESTIDO' },
  { text: 'POLOS' },
  { text: 'SHORTS' },
  { text: 'SUDADERA' },
  { text: 'TENIS' },
  { text: 'TOPS' },
  { text: 'VESTIDOS' },
  { text: 'VESTIDO_DE_BANO_BRASIER' },
  { text: 'VESTIDO_DE_BANO_TANGA' },
  { text: 'ZAPATOS' },
];

exports.mainColors = [
  {
    value: 'rojo',
    hexa: '#fd0000',
    rgb: '(253, 0, 0)',
    hsl: '(0, 100%, 50%)',
  },
  {
    value: 'amarillo',
    hexa: '#fdd500',
    rgb: '(253, 213, 0)',
    hsl: '(51, 100%, 50%)',
  },
  {
    value: 'azul',
    hexa: '#290c96',
    rgb: '( 41, 12, 150 )',
    hsl: '(253, 92%, 32%)',
  },
  {
    value: 'morado',
    hexa: '#7e0c96',
    rgb: '(126, 12, 150)',
    hsl: '(290, 92%, 32%)',
  },
  {
    value: 'naranjado',
    hexa: '#ec7335',
    rgb: '(236, 115, 53)',
    hsl: '(20, 78%, 57%)',
  },
  {
    value: 'verde',
    hexa: '#56a435',
    rgb: '(86, 164, 53)',
    hsl: '(102, 68%, 43%)',
  },
  {
    value: 'negro',
    hexa: '#000000',
    rgb: '(0, 0, 0)',
    hsl: '(0, 0%, 0%)',
  },
  {
    value: 'blanco',
    hexa: '#fffffe',
    rgb: '(255, 255, 254)',
    hsl: '(60, 0%, 100%)',
  },
  {
    value: 'gris',
    hexa: '#4b5154',
    rgb: '(75, 81, 84)',
    hsl: '(200, 11%, 31%)',
  },
  {
    value: 'beige',
    hexa: '#feffd4',
    rgb: '(254, 255, 212)',
    hsl: '(61, 17%, 92%)',
  },
  {
    value: 'rosado',
    hexa: '#fed4d4',
    rgb: '(254, 212, 212)',
    hsl: '( 0, 17%, 91% )',
  },
  {
    value: 'cafe',
    hexa: '#815140',
    rgb: '(129, 81, 64)',
    hsl: '(16, 50%, 38%)',
  },
];
