exports.prendasGenerales = [
  { text: 'BERMUDA' },
  { text: 'BODIES' },
  { text: 'BOLSO' },
  { text: 'BOXER' },
  { text: 'BRASIER' },
  { text: 'BUZOS' },
  { text: 'CHAQUETAS' },
  { text: 'CAMISAS' },
  { text: 'CAMISETAS' },
  { text: 'CROP_TOPS' },
  { text: 'ENTERIZO' },
  { text: 'FALDAS' },
  { text: 'JEANS' },
  { text: 'LEGINGS' },
  { text: 'OVEROLES' },
  { text: 'PANOLETAS' },
  { text: 'PANTALONES' },
  { text: 'PANTALONETAS' },
  { text: 'PANTIES' },
  { text: 'PIJAMAS_CAMISETAS' },
  { text: 'PIJAMAS_PANTALON' },
  { text: 'PIJAMAS_VESTIDO' },
  { text: 'POLOS' },
  { text: 'SHORTS' },
  { text: 'SUDADERA' },
  { text: 'TENIS' },
  { text: 'TOPS' },
  { text: 'VESTIDOS' },
  { text: 'VESTIDO_DE_BANO_BRASIER' },
  { text: 'VESTIDO_DE_BANO_TANGA' },
  { text: 'ZAPATOS' },
];

exports.mainColors = [
  {
    value: 'rojo',
    hexa: '#fd0000',
    rgb: '(253, 0, 0)',
    hsl: '(0, 100%, 50%)',
  },
  {
    value: 'amarillo',
    hexa: '#fdd500',
    rgb: '(253, 213, 0)',
    hsl: '(51, 100%, 50%)',
  },
  {
    value: 'azul',
    hexa: '#290c96',
    rgb: '( 41, 12, 150 )',
    hsl: '(253, 92%, 32%)',
  },
  {
    value: 'morado',
    hexa: '#7e0c96',
    rgb: '(126, 12, 150)',
    hsl: '(290, 92%, 32%)',
  },
  {
    value: 'naranjado',
    hexa: '#ec7335',
    rgb: '(236, 115, 53)',
    hsl: '(20, 78%, 57%)',
  },
  {
    value: 'verde',
    hexa: '#56a435',
    rgb: '(86, 164, 53)',
    hsl: '(102, 68%, 43%)',
  },
  {
    value: 'negro',
    hexa: '#000000',
    rgb: '(0, 0, 0)',
    hsl: '(0, 0%, 0%)',
  },
  {
    value: 'blanco',
    hexa: '#fffffe',
    rgb: '(255, 255, 254)',
    hsl: '(60, 0%, 100%)',
  },
  {
    value: 'gris',
    hexa: '#4b5154',
    rgb: '(75, 81, 84)',
    hsl: '(200, 11%, 31%)',
  },
  {
    value: 'beige',
    hexa: '#feffd4',
    rgb: '(254, 255, 212)',
    hsl: '(61, 17%, 92%)',
  },
  {
    value: 'rosado',
    hexa: '#fed4d4',
    rgb: '(254, 212, 212)',
    hsl: '( 0, 17%, 91% )',
  },
  {
    value: 'cafe',
    hexa: '#815140',
    rgb: '(129, 81, 64)',
    hsl: '(16, 50%, 38%)',
  },
];


exports.subCategoria = [
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa interior',
  'ropa interior',
  'ropa interior', 
  'ropa interior', 
  'ropa interior', 
  'calzado',
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'calzado',
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa interior',
  'calzado',
  'accesorios', 
  'accesorios',
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa interior',
  'ropa interior', 
  'ropa interior', 
  'ropa interior',
  'ropa interior', 
  'calzado',
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'calzado',
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa interior', 
  'ropa interior', 
  'ropa interior', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa interior',
  'ropa interior', 
  'ropa interior', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'calzado',
  'accesorios', 
  'accesorios', 
  'accesorios',
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'accesorios', 
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa interior',
  'ropa interior', 
  'ropa interior', 
  'ropa interior', 
  'ropa interior', 
  'accesorios',
  'calzado',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa exterior',
  'ropa interior',
  'ropa interior', 
  'ropa interior', 
  'accesorios',
  'ropa exterior',
  'calzado',
  'ropa exterior'
  
]

exports.tipoPrenda = [
  'chaquetas y chalecos',
  'cardigans y jerseis',
  'abrigos | trench',
  'camisas',
  'camisetas',
  'polos',
  'jeans',
  'pantalones',
  'joggers',
  'shorts',
  'bermudas', 
  'faldas',
  'vestidos',
  'chaquetas',
  'buzos',
  'pijamas',
  'panties',
  'brassier',
  'tops',
  'medias',
  'calzado',
  'bolsos',
  'bisutería',
  'cuidado personal',
  'relojes',
  'otros accesorios',
  'blazers',
  'chalecos',
  'cazadoras',
  'sobrecamisas',
  'bombers',
  'abrigos',
  'trench',
  'plumiferos', 
  'acolchados',
  'chalecos',
  'vestidos', 
  'monos',
  'tops',
  'camisas',
  'bluzas',
  'camisetas',
  'sudaderas',
  'polo',
  'pantalones',
  'pantalones de vestir',
  'leggings',
  'joggers',
  'fluidos',
  'jeans',
  'faldas',
  'bermudas',
  'zapatos',
  'bolsos',
  'pet collectionnew',
  'yoga collectionnew',
  'perfumes',
  'bisutería',
  'cinturones',
  'gorros | sombreros',
  'pañuelos',
  'gafas de sol',
  'calcetines',
  'perfumes',
  'abrigos',
  'chaquetas',
  'jerséis',
  'cardigans',
  'chalecos', 
  'americanas',
  'acolchadas',
  'cazadoras',
  'sobrecamisas',
  'vaqueras',
  'piel',
  'vestidos', 
  'monos',
  'camisas',
  'bluzas',
  'camisetas', 
  'tops',
  'sudaderas',
  'pantalones',
  'leggings',
  'joggers',
  'vaqueros',
  'faldas',
  'shorts',
  'bodys',
  'zapatos',
  'bolsos',
  'paraguas',
  'calcetines',
  'accesosorios para el pelo',
  'otros accesorios',
  'gorros', 
  'mascarillas', 
  'bufandas',
  'pañuelos',
  'bisutería',
  'marroquinería',
  'cinturones',
  'gafas de sol',
  'camisas',
  'camisetas',
  'polos',
  'jeans',
  'pantalones',
  'joggers',
  'bermudas',
  'buzos',
  'chaquetas',
  'pijamas',
  'bóxer',
  'pantaloncillos',
  'camisetas',
  'medias',
  'calzado',
  'correas',
  'gorras',
  'relojes',
  'otros accesorios',
  'gabardinas',
  'abrigos',
  'parkas',
  'trench',
  'cazadoras',
  'sobrecamisas',
  'chalecos',
  'blazers',
  'jerséis',
  'chaquetas',
  'cardigans',
  'chándal',
  'sudaderas',
  'camisas',
  'camisetas',
  'polos',
  'pantalones',
  'joggers',
  'chinos',
  'jeans',
  'bermudas',
  'zapatos',
  'bolsos',
  'mochilas',
  'perfumes',
  'gorras y gorros',
  'gafas de sol',
  'boxer',
  'pijamas',
  'calcetines',
  'corbatas y pajaritas',
  'cinturones',
  'porta teléfonos y accesorios',
  'carteras',
  'bufandas y foulards',
  'bisuteria', 
  'relojes',
  'pet collectionnew',
  'abrigos',
  'chaquetas',
  'cardigans', 
  'jerseis',
  'chalecos',
  'trench',
  'parkas',
  'camisas',
  'pantalones',
  'vaqueros',
  'sobrecamisas',
  'americanas',
  'sudaderas',
  'camisetas',
  'bañadores',
  'pijamas', 
  'calzoncillos',
  'calcetines', 
  'americanas',
  'pantalones',
  'camisas',
  'zapatos',
  'mochilas',
  'bolsos',
  'carteras',
  'bufandas', 
  'fulares',
  'gorros', 
  'guantes', 
  'cinturones',
  'tirantes', 
  'corbatas', 
  'pajaritas',
  'gafas de sol',
  'pulseras', 
  'anillos',
  'más accesorios',
  'camisas',
  'camisetas',
  'pantalones',
  'jeans', 
  'leggins',
  'shorts',
  'faldas',
  'vestidos', 
  'buzos',
  'chaquetas', 
  'conjuntos',
  'pijamas',
  'tops',
  'panties',
  'vestido de baño',
  'medias',
  'accesorios',
  'zapatos',
  'camisas',
  'camisetas',
  'polos',
  'pantalones',
  'jeans',
  'joggers',
  'bermudas',
  'buzos',
  'chaquetas',
  'conjuntos',
  'pijamas',
  'boxer',
  'medias',
  'accesorios',
  'beachwear',
  'calzado',
  'trench y parkas'

]

exports.colorSinHomologar = [
'amarillo',
'arena',
'azul',
'beige',
'blanco',
'burdeos',
'camel',
'caramelo',
'cereza',
'chocolate',
'cobre',
'cognac',
'crudo',
'denim',
'esmeralda',
'fresa',
'fucsia',
'granate',
'gris',
'khaki',
'lila',
'lima',
'mandarina',
'marrón',
'melocotón',
'morado',
'mostaza',
'naranja',
'negro',
'nude',
'ocre',
'oliva',
'oro',
'piedra',
'pimentón',
'plata',
'pomelo',
'púrpura',
'rojo',
'rosa',
'salmón',
'topo',
'turquesa',
'vainilla',
'verde',
'vino',
'acero',
'amarillo',
'antracita',
'añil',
'arcilla',
'arena',
'azul',
'azulado',
'azulón',
'beige',
'berenjena',
'blanco',
'burdeos',
'calabaza',
'caldero',
'caramelo',
'carbón',
'celeste',
'césped',
'ciruela',
'cobalto',
'crema',
'cristal',
'crudo',
'crudo/amarillo',
'dorado',
'estampado',
'fresa',
'fucsia',
'granate',
'gris',
'grises',
'hielo',
'kaki',
'khaki',
'leopardo',
'lila',
'lima',
'magenta',
'malva',
'mantequilla',
'marino',
'marinos',
'marrón',
'melocotón',
'menta',
'morado',
'mostaza',
'multicolor',
'naranja',
'naranja-verde',
'natural',
'negro',
'ocre',
'oliva',
'oro',
'piedra',
'plata',
'plomo',
'rojo',
'rosa',
'rosado',
'rosas',
'teja',
'terracota',
'tierra',
'toffe',
'tostado',
'turquesa',
'único',
'vainilla',
'varios',
'verde',
'verde-seco',
'verdoso',
'vino',
'violeta',
'visón'
]

exports.colorHomologado = [
'amarillo',
'beige',
'azul',
'beige',
'blanco',
'vinotinto',
'café',
'café',
'vinotinto',
'café',
'cobre', 
'café',
'beige',
'negro',
'verde',
'rosado',
'rosado',
'Vinotinto',
'gris',
'verde',
'morado',
'verde',
'naranja',
'café',
'naranja',
'morado',
'amarillo',
'naranja',
'negro',
'piel',
'ocre',
'verde',
'oro',
'beige',
'rojo',
'plata',
'piel',
'morado',
'rojo',
'rosado',
'piel',
'café',
'azul',
'beige',
'verde',
'vinotinto',
'acero',
'amarillo',
'gris',
'azul',
'gris',
'beige',
'azul',
'azul',
'azul',
'beige',
'vinotinto',
'blanco',
'vinotinto',
'naranja',
'naranja',
'café',
'negro',
'azul',
'verde',
'Vinotinto',
'azul',
'beige',
'transparente', 
'beige',
'beige',
'dorado',
'multicolor',
'rosado',
'rosado',
'vinotinto',
'gris',
'gris',
'azul',
'verde',
'verde',
'otros', 
'morado',
'verde',
'morado',
'morado',
'beige',
'azul',
'azul',
'café',
'naranja',
'verde',
'morado',
'amarillo',
'multicolor',
'naranja', 
'naranja', 
'beige',
'negro',
'ocre',
'verde',
'oro',
'beige',
'plata',
'plomo',
'rojo',
'rosado',
'rosado',
'rosado',
'naranja',
'naranja',
'café',
'café',
'café',
'morado',
'multicolor', 
'beige',
'multicolor',
'verde',
'verde',
'verde',
'vinotinto',
'morado',
'café'

]

// colores sin repetir
exports.colorSinRepetir = [
  'amarillo',
  'beige',
  'azul',
  'blanco',
  'vinotinto',
  'café',
  'cobre',
  'negro',
  'verde',
  'rosado',
  'gris',
  'morado',
  'naranja',
  'piel',
  'ocre',
  'oro',
  'rojo',
  'plata',
  'acero',
  'transparente',
  'dorado',
  'multicolor',
  'otros',
  'plomo',
  'café'
]

// colores en formato hex
exports.colorHEX = [
  '#FFFF00',
  '#CD853F',
  '#1E90FF',
  '#FFFFFF',
  '#820000',
  '#A0522D',
  '#CB6D51',
  '#000000',
  '#008000',
  '#FFC0CB',
  '#A9A9A9',
  '#663399',
  '#FF4500',
  '#fdddca',
  '#b9935a',
  '#ffbf00',
  '#FF0000',
  '#BEBEBE',
  '#434b4d',
  '#00F0F8FF',
  '#a98307',
  '#BF85A5',
  '#85A8BF',
  '#cdcdcd',
  '#A0522D'
]